---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-example-controller
  namespace: default
  labels:
    api: my-example
    controller: "true"
spec:
  selector:
    matchLabels:
      api: my-example
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: my-example
        controller: "true"
    spec:
      containers:
      - name: controller
        image: harbor.shopeemobile.com/ecp/irmas/sxy_apiserver_test:1.0.0
        command:
        - "./controller-manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: my-example
